### PR TITLE
Add support for linux terminals

### PR DESCRIPTION
**Pull request by chocorho**
I attempt to use GLibC function calls (first termios and then ioctl) in order to get relevant terminal width/height data on Linux systems.

Please do build and test before merging. Then you/we might want to remove the old termios attempt if it is outdated.

### CODE REVIEW

**Comment by suwuako** [comment]
hmm - windows refuses to compile since it doesnt have ioctl.h 
```g++ .\cube_windows.cpp
.\cube_windows.cpp:9:12: fatal error: sys/ioctl.h: No such file or directory
    9 |   #include <sys/ioctl.h>
      |            ^~~~~~~~~~~~~
compilation terminated.```

**Comment by suwuako** [comment]
compiles and runs fine on my linux machine, not windows

**Comment by suwuako** [comment]
for now I'm putting this on hold until i figure out how to include linux headers

**Comment by chocorho** [comment]
> hmm - windows refuses to compile since it doesnt have ioctl.h
> 
> ```
> .\cube_windows.cpp:9:12: fatal error: sys/ioctl.h: No such file or directory
>     9 |   #include <sys/ioctl.h>
>       |            ^~~~~~~~~~~~~
> compilation terminated.```
> ```

This is odd, because I deliberately tried to use preprocessor macros to ensure that the compiler does not even **try** to include that header file when compiling for Windows. I hesitantly chose `_MSC_VER` because that's what worked on my older projects, like the MGG.

Clearly, there must be a better alternative to check whether your system is Windows. Maybe it is [_WIN32](https://stackoverflow.com/a/2348852)? If you replace that macro, does it work?

Out of curiosity, what compiler name/version are you using? That might help me to identify the appropriate macro name.

**Comment by suwuako** [comment]
good suggestion - i changed the header guard and it compiles successfully. But seems like using different headers causes different issues later on in the code: we probably need to fix this

```cpp
g++ .\cube_windows.cpp
.\cube_windows.cpp: In function 'void get_screen_size(int*)':
.\cube_windows.cpp:114:18: error: aggregate 'get_screen_size(int*)::winsize size_info' has incomplete type and cannot be defined
  114 |   struct winsize size_info;
      |                  ^~~~~~~~~
.\cube_windows.cpp:117:37: error: 'TIOCGWINSZ' was not declared in this scope
  117 |   int err_code = ioctl(demanded_fd, TIOCGWINSZ, &size_info); // &columns, &rows); // tcgetattr(demanded_fd, &attrib_struct);
      |                                     ^~~~~~~~~~
.\cube_windows.cpp:117:18: error: 'ioctl' was not declared in this scope
  117 |   int err_code = ioctl(demanded_fd, TIOCGWINSZ, &size_info); // &columns, &rows); // tcgetattr(demanded_fd, &attrib_struct);
      |                  ^~~~~
.\cube_windows.cpp: In function 'void loop(int, int, int, double*, double (*)[3])':
.\cube_windows.cpp:466:5: error: 'sleep' was not declared in this scope; did you mean 'Sleep'?
  466 |     sleep(1);
      |     ^~~~~
      |     Sleep```

**Comment by suwuako** [comment]
whoops, sorry forgot to also edit the header guards for the `get_screen_size` function - fixed it and will push after this comment. Still facing an issue with the sleep function since for windows its `Sleep()` whilst for linux its `sleep()`. Should be an easy fix.

**Comment by suwuako** [comment]
Compiles & runs fine on my end - can you check if the patches compiles and runs on yours? Ill merge if it does properly :D

**Comment by suwuako** [comment]
also - is there a better way to do this? its a bit of an eyesore on the code lol. I mean if it works it works tho ill still merge it

**Comment by chocorho** [comment]
Yep, I just confirmed it compiles and runs fine on my Linux machine. And, if there is a more "elegant" way to do it without using preprocessor macros, then I certainly have not been exposed to itin eight years. I wish there were a better way, but if it were me, I would go forward with this.

**Comment by suwuako** [comment]
fair enough, ive merged it into main. Thanks for the PR! :D

**Pull request merged**
